name: CustomTP
author: zwoosks
main: me.zwoosks.CustomTP
version: 1.0.0
description: Create custom TPs!
commands:
   createcustomtp:
      aliases: cctp
      description: Create your CTP!
      usage: /<command>
   customtp:
      aliases: ctp
      description: Teleport to a CTP!
      usage: /<command> (user)
   ctphelp:
      aliases: ctph
      description: CustomTP help.
      usage: /<command>